/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;

import Controllers.GUIController;

/**
 *
 * @author steev_000
 */
public class JPanelLogin extends javax.swing.JPanel {

  /**
   * Creates new form NewJPanel
   */
  public JPanelLogin() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jLabelUsername = new javax.swing.JLabel();
    jLabelPassword = new javax.swing.JLabel();
    jBtnLogin = new javax.swing.JButton();
    jLabel3 = new javax.swing.JLabel();
    jTxtUsername = new javax.swing.JTextField();
    jPwdPassword = new javax.swing.JPasswordField();
    jLblError = new javax.swing.JLabel();

    jPanel1.setPreferredSize(new java.awt.Dimension(736, 145));

    jLabelUsername.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
    jLabelUsername.setText("Username:");

    jLabelPassword.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
    jLabelPassword.setText("Password:");

    jBtnLogin.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
    jBtnLogin.setText("Login");
    jBtnLogin.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jBtnLoginActionPerformed(evt);
      }
    });

    jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
    jLabel3.setText("Login");

    jTxtUsername.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
    jTxtUsername.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jTxtUsernameActionPerformed(evt);
      }
    });

    jPwdPassword.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(260, 260, 260)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel3)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabelPassword)
              .addComponent(jLabelUsername))
            .addGap(18, 18, 18)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(jTxtUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
              .addComponent(jPwdPassword)))
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(20, 20, 20)
            .addComponent(jBtnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap(264, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel3)
        .addGap(15, 15, 15)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabelUsername)
          .addComponent(jTxtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabelPassword)
          .addComponent(jPwdPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jBtnLogin)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jLblError.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
    jLblError.setForeground(new java.awt.Color(255, 51, 51));
    jLblError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap(207, Short.MAX_VALUE)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(201, 201, 201))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addComponent(jLblError, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(409, 409, 409))))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(113, 113, 113)
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jLblError)
        .addContainerGap(128, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents

  private void jBtnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLoginActionPerformed
    /*if(jTxtUsername.getText().isEmpty() && jPwdPassword.getText().isEmpty()) {
      jLblError.setText("Please enter a usename and password!");
    } else if(jTxtUsername.getText().isEmpty()) {
      jLblError.setText("Please enter a username!");
    } else if(jPwdPassword.getText().isEmpty()) {
      jLblError.setText("Please enter a password!");
    } else {
      
      //if(jPwdPassword.getText().equals(GUIController.db.getPassword(jTxtUsername.getText()))) {
      if(GUIController.users.validateLogin(jTxtUsername.getText(), jPwdPassword.getText())) {
        jTxtUsername.setText(null);
        jPwdPassword.setText(null);
        
        GUIController.switchTo("HOME");
      } else {
        jLblError.setText("Username or password is incorrect!");
        jPwdPassword.setText(null);
      }
    }
  */
    GUIController.switchTo(("HOME"));
  }//GEN-LAST:event_jBtnLoginActionPerformed

  private void jTxtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtUsernameActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_jTxtUsernameActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jBtnLogin;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabelPassword;
  private javax.swing.JLabel jLabelUsername;
  private javax.swing.JLabel jLblError;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPasswordField jPwdPassword;
  private javax.swing.JTextField jTxtUsername;
  // End of variables declaration//GEN-END:variables
}
