/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author cabro_000
 */
public class JPanelDeleteAccount extends javax.swing.JPanel {

    /**
     * Creates new form JPanelDeleteAccount
     */
    public JPanelDeleteAccount() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel3 = new javax.swing.JLabel();
    jComBoxUserDA = new javax.swing.JComboBox();
    jLabelUsername2 = new javax.swing.JLabel();
    jBtnDeleteUserDA = new javax.swing.JButton();
    jBtnCancelDA = new javax.swing.JButton();
    jBtnLogoutDA = new javax.swing.JButton();

    jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
    jLabel3.setText("Delete User Account");

    jComBoxUserDA.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
    jComBoxUserDA.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select User Account", "Cho, I", "Hallouche, F", "Corser, G" }));

    jLabelUsername2.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
    jLabelUsername2.setText("User Account:");

    jBtnDeleteUserDA.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
    jBtnDeleteUserDA.setText("Delete User Account");
    jBtnDeleteUserDA.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jBtnDeleteUserDAActionPerformed(evt);
      }
    });

    jBtnCancelDA.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
    jBtnCancelDA.setText("Cancel");

    jBtnLogoutDA.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
    jBtnLogoutDA.setText("Logout");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtnLogoutDA))
              .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelUsername2)
                .addGap(21, 21, 21)
                .addComponent(jComBoxUserDA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 7, Short.MAX_VALUE)))
            .addContainerGap())
          .addGroup(layout.createSequentialGroup()
            .addComponent(jBtnDeleteUserDA)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jBtnCancelDA)
            .addGap(0, 0, Short.MAX_VALUE))))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel3)
          .addComponent(jBtnLogoutDA))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jComBoxUserDA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabelUsername2))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jBtnDeleteUserDA)
          .addComponent(jBtnCancelDA))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents

    private void jBtnDeleteUserDAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDeleteUserDAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnDeleteUserDAActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jBtnCancelDA;
  private javax.swing.JButton jBtnDeleteUserDA;
  private javax.swing.JButton jBtnLogoutDA;
  private javax.swing.JComboBox jComBoxUserDA;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabelUsername2;
  // End of variables declaration//GEN-END:variables
}
