/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;

/**
 *
 * @author Steve
 */
public class JPanelCourseListing extends javax.swing.JPanel {

    /**
     * Creates new form JPanelCourseListing
     */
    public JPanelCourseListing() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jLabel3 = new javax.swing.JLabel();
    jScrollPane1 = new javax.swing.JScrollPane();
    jTableCourseListing = new javax.swing.JTable();
    jBtnBackCL = new javax.swing.JButton();
    jBtnModifyCL = new javax.swing.JButton();
    jBtnAddCL = new javax.swing.JButton();
    jLabelUsername = new javax.swing.JLabel();

    setPreferredSize(new java.awt.Dimension(736, 401));

    jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
    jLabel3.setText("Course Listing Results");

    jTableCourseListing.setAutoCreateRowSorter(true);
    jTableCourseListing.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
    jTableCourseListing.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {"CS471", "Senior CS Capstone",  new Integer(732), "I. Cho", "MW", "12:30-2:20", "SE117", "8"}
      },
      new String [] {
        "Course #", "Name", "Line No.", "Professor", "Days", "Time", "Room", "Students"
      }
    ) {
      Class[] types = new Class [] {
        java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
      };
      boolean[] canEdit = new boolean [] {
        false, false, false, false, false, false, false, false
      };

      public Class getColumnClass(int columnIndex) {
        return types [columnIndex];
      }

      public boolean isCellEditable(int rowIndex, int columnIndex) {
        return canEdit [columnIndex];
      }
    });
    jScrollPane1.setViewportView(jTableCourseListing);

    jBtnBackCL.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
    jBtnBackCL.setText("Back");
    jBtnBackCL.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jBtnBackCLActionPerformed(evt);
      }
    });

    jBtnModifyCL.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
    jBtnModifyCL.setText("Modify Selected Course");
    jBtnModifyCL.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jBtnModifyCLActionPerformed(evt);
      }
    });

    jBtnAddCL.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
    jBtnAddCL.setText("Add New Course");
    jBtnAddCL.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jBtnAddCLActionPerformed(evt);
      }
    });

    jLabelUsername.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
    jLabelUsername.setText("1 Course(s) Found");

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel3)
          .addComponent(jLabelUsername)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(10, 10, 10)
            .addComponent(jBtnBackCL)
            .addGap(18, 18, 18)
            .addComponent(jBtnModifyCL)
            .addGap(18, 18, 18)
            .addComponent(jBtnAddCL))
          .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 711, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel3)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabelUsername)
        .addGap(5, 5, 5)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jBtnAddCL)
          .addComponent(jBtnModifyCL)
          .addComponent(jBtnBackCL))
        .addContainerGap(22, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );
  }// </editor-fold>//GEN-END:initComponents

  private void jBtnModifyCLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnModifyCLActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_jBtnModifyCLActionPerformed

  private void jBtnAddCLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAddCLActionPerformed
    CSMS.switchTo("NEW SECTION");
  }//GEN-LAST:event_jBtnAddCLActionPerformed

  private void jBtnBackCLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBackCLActionPerformed
    CSMS.switchTo("COURSE SEARCH");
  }//GEN-LAST:event_jBtnBackCLActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jBtnAddCL;
  private javax.swing.JButton jBtnBackCL;
  private javax.swing.JButton jBtnModifyCL;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabelUsername;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTable jTableCourseListing;
  // End of variables declaration//GEN-END:variables
}
