/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author cabro_000
 */
public class JPanelUpdateAccount extends javax.swing.JPanel {

    /**
     * Creates new form JPanelUpdateAccount
     */
    public JPanelUpdateAccount() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabelUsername2 = new javax.swing.JLabel();
    jLabelUsername11 = new javax.swing.JLabel();
    jtxtFirstNameUA = new javax.swing.JTextField();
    jtxtConfirmPasswordUA = new javax.swing.JTextField();
    jLabelUsername3 = new javax.swing.JLabel();
    jtxtMidInitialUA = new javax.swing.JTextField();
    jLabelUsername4 = new javax.swing.JLabel();
    jtxtLastNameUA = new javax.swing.JTextField();
    jLabelEditUA = new javax.swing.JLabel();
    jLabelUsername6 = new javax.swing.JLabel();
    jComBoxPositionUA = new javax.swing.JComboBox();
    jLabelUsername7 = new javax.swing.JLabel();
    jtxtMonikerUA = new javax.swing.JTextField();
    jBtnCancelUA = new javax.swing.JButton();
    jLabelUsername8 = new javax.swing.JLabel();
    jComBoxDeptUA = new javax.swing.JComboBox();
    jLabelUsername9 = new javax.swing.JLabel();
    jtxtEmailUA = new javax.swing.JTextField();
    jLabelUsername10 = new javax.swing.JLabel();
    jtxtPasswordUA = new javax.swing.JTextField();
    jBtnAddUserUA = new javax.swing.JButton();
    jBtnLogoutUA = new javax.swing.JButton();

    jLabelUsername2.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
    jLabelUsername2.setText("First Name: ");

    jLabelUsername11.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
    jLabelUsername11.setText("Confirm Password:");

    jLabelUsername3.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
    jLabelUsername3.setText("Middle Initial:");

    jLabelUsername4.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
    jLabelUsername4.setText("Last Name:");

    jLabelEditUA.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
    jLabelEditUA.setText("Edit User Account");

    jLabelUsername6.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
    jLabelUsername6.setText("Position:");

    jComBoxPositionUA.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
    jComBoxPositionUA.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Position", "Associate Professor", "Assistant Professor", "Adjunct Faculty", "Department Chair", "Professor" }));

    jLabelUsername7.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
    jLabelUsername7.setText("Moniker:");

    jBtnCancelUA.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
    jBtnCancelUA.setText("Cancel");

    jLabelUsername8.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
    jLabelUsername8.setText("Department:");

    jComBoxDeptUA.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
    jComBoxDeptUA.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Dept.", "Accounting", "Art", "Biology", "Black Studies", "Col Business & Management", "Communication & Digital Media", "Chemistry", "Computer Info Syst", "Criminal Justice", "Communication", "Computer Science", "Elec & Computer Engr", "Economics", "Education Leadership", "English Lang Program", "English", "Educational Tech & Development", "Engineering Tech Management", "Finance", "French", "Geography", "German", "Gender Studies", "History", "Honors", "Health Sciences", "Japanese", "Kinesiology", "Latin", "Law", "Leadership and Service", "Administrative Science", "Mathematical Sciences", "Mechanical Engr", "Master of Energy & Materials", "Modern Foreign Lang", "Management", "Marketing", "Medical Laboratory Science", "Music Education", "Music", "Natural Science", "Nursing", "Occupational Therapy", "Philosophy", "Physics", "Political Science", "Psychology", "Robert Fellows Seminar", "Rhetoric & Prof Writing", "Sociology", "Spanish", "Social Work", "Teaching Chinese As a Foreign", "Teacher Education--Mis/Sec Sch", "Teacher Education", "Theater", "Youth Services" }));

    jLabelUsername9.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
    jLabelUsername9.setText("E-Mail:");

    jLabelUsername10.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
    jLabelUsername10.setText("Password:");

    jBtnAddUserUA.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
    jBtnAddUserUA.setText("Create User Account");
    jBtnAddUserUA.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jBtnAddUserUAActionPerformed(evt);
      }
    });

    jBtnLogoutUA.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
    jBtnLogoutUA.setText("Logout");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(jLabelEditUA)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jBtnLogoutUA))
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabelUsername2)
              .addComponent(jLabelUsername3)
              .addComponent(jLabelUsername4)
              .addComponent(jLabelUsername10)
              .addComponent(jLabelUsername9)
              .addComponent(jLabelUsername8)
              .addComponent(jLabelUsername7)
              .addComponent(jLabelUsername6)
              .addComponent(jLabelUsername11))
            .addGap(26, 26, 26)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jtxtFirstNameUA, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addComponent(jtxtMidInitialUA, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jtxtLastNameUA, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jtxtPasswordUA, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jtxtEmailUA, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jComBoxDeptUA, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jtxtMonikerUA, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jComBoxPositionUA, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jtxtConfirmPasswordUA, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(0, 0, Short.MAX_VALUE)))
        .addContainerGap())
      .addGroup(layout.createSequentialGroup()
        .addGap(32, 32, 32)
        .addComponent(jBtnAddUserUA)
        .addGap(35, 35, 35)
        .addComponent(jBtnCancelUA)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabelEditUA)
          .addComponent(jBtnLogoutUA))
        .addGap(13, 13, 13)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jtxtFirstNameUA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabelUsername2))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jtxtMidInitialUA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabelUsername3))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jtxtLastNameUA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabelUsername4))
        .addGap(8, 8, 8)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jComBoxPositionUA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabelUsername6))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jtxtMonikerUA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabelUsername7))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jComBoxDeptUA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabelUsername8))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jtxtEmailUA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabelUsername9))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jtxtPasswordUA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabelUsername10))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(jLabelUsername11)
          .addComponent(jtxtConfirmPasswordUA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jBtnAddUserUA)
          .addComponent(jBtnCancelUA))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents

    private void jBtnAddUserUAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAddUserUAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnAddUserUAActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jBtnAddUserUA;
  private javax.swing.JButton jBtnCancelUA;
  private javax.swing.JButton jBtnLogoutUA;
  private javax.swing.JComboBox jComBoxDeptUA;
  private javax.swing.JComboBox jComBoxPositionUA;
  private javax.swing.JLabel jLabelEditUA;
  private javax.swing.JLabel jLabelUsername10;
  private javax.swing.JLabel jLabelUsername11;
  private javax.swing.JLabel jLabelUsername2;
  private javax.swing.JLabel jLabelUsername3;
  private javax.swing.JLabel jLabelUsername4;
  private javax.swing.JLabel jLabelUsername6;
  private javax.swing.JLabel jLabelUsername7;
  private javax.swing.JLabel jLabelUsername8;
  private javax.swing.JLabel jLabelUsername9;
  private javax.swing.JTextField jtxtConfirmPasswordUA;
  private javax.swing.JTextField jtxtEmailUA;
  private javax.swing.JTextField jtxtFirstNameUA;
  private javax.swing.JTextField jtxtLastNameUA;
  private javax.swing.JTextField jtxtMidInitialUA;
  private javax.swing.JTextField jtxtMonikerUA;
  private javax.swing.JTextField jtxtPasswordUA;
  // End of variables declaration//GEN-END:variables
}
