/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;

import javax.swing.JOptionPane;

/**
 *
 * @author steev_000
 */
public class JPanelRequiredChanges extends javax.swing.JPanel {

  /**
   * Creates new form JPanelRequiredChanges
   */
  public JPanelRequiredChanges() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jLabel3 = new javax.swing.JLabel();
    jLabelConflicts = new javax.swing.JLabel();
    jScrollPane3 = new javax.swing.JScrollPane();
    jTable1 = new javax.swing.JTable();
    jBtnBackSS = new javax.swing.JButton();
    jBtnManual = new javax.swing.JButton();

    jPanel1.setPreferredSize(new java.awt.Dimension(731, 401));

    jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
    jLabel3.setText("Required Changes");

    jLabelConflicts.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
    jLabelConflicts.setText("The following changes will be made to resolve the schedule conflicts");

    jTable1.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {"CS216",  new Integer(1), "WI/15", "Room = SE115"}
      },
      new String [] {
        "Course", "Section", "Term", "Changes"
      }
    ) {
      Class[] types = new Class [] {
        java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
      };

      public Class getColumnClass(int columnIndex) {
        return types [columnIndex];
      }
    });
    jScrollPane3.setViewportView(jTable1);

    jBtnBackSS.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
    jBtnBackSS.setText("Back");

    jBtnManual.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
    jBtnManual.setText("Commit Changes");
    jBtnManual.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jBtnManualActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabel3)
              .addComponent(jLabelConflicts)
              .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jBtnBackSS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnManual)))
            .addGap(0, 327, Short.MAX_VALUE))
          .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 711, Short.MAX_VALUE))
        .addContainerGap())
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel3)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabelConflicts)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jBtnBackSS)
          .addComponent(jBtnManual))
        .addGap(33, 33, 33))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );
  }// </editor-fold>//GEN-END:initComponents

  private void jBtnManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnManualActionPerformed
    JOptionPane.showMessageDialog(null, "All conflicts have been resolved!");
    CSMS.switchTo("HOME");
  }//GEN-LAST:event_jBtnManualActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jBtnBackSS;
  private javax.swing.JButton jBtnManual;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabelConflicts;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JScrollPane jScrollPane3;
  private javax.swing.JTable jTable1;
  // End of variables declaration//GEN-END:variables
}
