/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CSSCS421;

/**
 *
 * @author cabro_000
 */
public class JPanelNewUserAccount extends javax.swing.JPanel {

    /**
     * Creates new form JPanelNewUserAccount
     */
    public JPanelNewUserAccount() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelUsername5 = new javax.swing.JLabel();
        jtxtNameMod4 = new javax.swing.JTextField();
        jBtnAddUserNA = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jBtnCancelNA = new javax.swing.JButton();
        jLabelUsername2 = new javax.swing.JLabel();
        jtxtFirstNameNA = new javax.swing.JTextField();
        jLabelUsername3 = new javax.swing.JLabel();
        jtxtMidInitialNA = new javax.swing.JTextField();
        jLabelUsername4 = new javax.swing.JLabel();
        jtxtLastNameNA = new javax.swing.JTextField();
        jLabelUsername6 = new javax.swing.JLabel();
        jComBoxPositionNA = new javax.swing.JComboBox();
        jLabelUsername7 = new javax.swing.JLabel();
        jtxtMonikerNA = new javax.swing.JTextField();
        jLabelUsername8 = new javax.swing.JLabel();
        jComBoxDeptNA = new javax.swing.JComboBox();
        jLabelUsername9 = new javax.swing.JLabel();
        jtxtEmailNA = new javax.swing.JTextField();
        jLabelUsername10 = new javax.swing.JLabel();
        jtxtPasswordNA = new javax.swing.JTextField();
        jLabelUsername11 = new javax.swing.JLabel();
        jtxtConfirmPasswordNA = new javax.swing.JTextField();

        jLabelUsername5.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabelUsername5.setText("Last Name:");

        jBtnAddUserNA.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jBtnAddUserNA.setText("Create User Account");

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel3.setText("Create User Account");

        jBtnCancelNA.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jBtnCancelNA.setText("Cancel");

        jLabelUsername2.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabelUsername2.setText("First Name: ");

        jLabelUsername3.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabelUsername3.setText("Middle Initial:");

        jLabelUsername4.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabelUsername4.setText("Last Name:");

        jLabelUsername6.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabelUsername6.setText("Position:");

        jComBoxPositionNA.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jComBoxPositionNA.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Position", "Associate Professor", "Assistant Professor", "Adjunct Faculty", "Department Chair", "Professor" }));

        jLabelUsername7.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabelUsername7.setText("Moniker:");

        jLabelUsername8.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabelUsername8.setText("Department:");

        jComBoxDeptNA.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jComBoxDeptNA.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Dept.", "Accounting", "Art", "Biology", "Black Studies", "Col Business & Management", "Communication & Digital Media", "Chemistry", "Computer Info Syst", "Criminal Justice", "Communication", "Computer Science", "Elec & Computer Engr", "Economics", "Education Leadership", "English Lang Program", "English", "Educational Tech & Development", "Engineering Tech Management", "Finance", "French", "Geography", "German", "Gender Studies", "History", "Honors", "Health Sciences", "Japanese", "Kinesiology", "Latin", "Law", "Leadership and Service", "Administrative Science", "Mathematical Sciences", "Mechanical Engr", "Master of Energy & Materials", "Modern Foreign Lang", "Management", "Marketing", "Medical Laboratory Science", "Music Education", "Music", "Natural Science", "Nursing", "Occupational Therapy", "Philosophy", "Physics", "Political Science", "Psychology", "Robert Fellows Seminar", "Rhetoric & Prof Writing", "Sociology", "Spanish", "Social Work", "Teaching Chinese As a Foreign", "Teacher Education--Mis/Sec Sch", "Teacher Education", "Theater", "Youth Services" }));

        jLabelUsername9.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabelUsername9.setText("E-Mail:");

        jLabelUsername10.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabelUsername10.setText("Password:");

        jLabelUsername11.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabelUsername11.setText("Confirm Password:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelUsername2)
                            .addComponent(jLabelUsername3)
                            .addComponent(jLabelUsername4)
                            .addComponent(jLabelUsername10)
                            .addComponent(jLabelUsername9)
                            .addComponent(jLabelUsername8)
                            .addComponent(jLabelUsername7)
                            .addComponent(jLabelUsername6)
                            .addComponent(jLabelUsername11))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jtxtFirstNameNA, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jtxtMidInitialNA, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtLastNameNA, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtPasswordNA, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtEmailNA, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComBoxDeptNA, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtMonikerNA, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComBoxPositionNA, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtConfirmPasswordNA, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jBtnAddUserNA)
                .addGap(35, 35, 35)
                .addComponent(jBtnCancelNA)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtFirstNameNA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelUsername2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtMidInitialNA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelUsername3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtLastNameNA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelUsername4))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComBoxPositionNA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelUsername6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtMonikerNA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelUsername7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComBoxDeptNA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelUsername8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtEmailNA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelUsername9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtPasswordNA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelUsername10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelUsername11)
                    .addComponent(jtxtConfirmPasswordNA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnAddUserNA)
                    .addComponent(jBtnCancelNA))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAddUserNA;
    private javax.swing.JButton jBtnCancelNA;
    private javax.swing.JComboBox jComBoxDeptNA;
    private javax.swing.JComboBox jComBoxPositionNA;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelUsername10;
    private javax.swing.JLabel jLabelUsername11;
    private javax.swing.JLabel jLabelUsername2;
    private javax.swing.JLabel jLabelUsername3;
    private javax.swing.JLabel jLabelUsername4;
    private javax.swing.JLabel jLabelUsername5;
    private javax.swing.JLabel jLabelUsername6;
    private javax.swing.JLabel jLabelUsername7;
    private javax.swing.JLabel jLabelUsername8;
    private javax.swing.JLabel jLabelUsername9;
    private javax.swing.JTextField jtxtConfirmPasswordNA;
    private javax.swing.JTextField jtxtEmailNA;
    private javax.swing.JTextField jtxtFirstNameNA;
    private javax.swing.JTextField jtxtLastNameNA;
    private javax.swing.JTextField jtxtMidInitialNA;
    private javax.swing.JTextField jtxtMonikerNA;
    private javax.swing.JTextField jtxtNameMod4;
    private javax.swing.JTextField jtxtPasswordNA;
    // End of variables declaration//GEN-END:variables
}
