/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package CSSCS421;

/**
 *
 * @author steev_000
 */
public class JPanelChooseSchedule extends javax.swing.JPanel {

  /**
   * Creates new form JPanelChooseSchedule
   */
  public JPanelChooseSchedule() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jLabel3 = new javax.swing.JLabel();
    jScrollPane1 = new javax.swing.JScrollPane();
    jTableCourseListing = new javax.swing.JTable();
    jBtnBackSS = new javax.swing.JButton();
    jBtnSubmitSS = new javax.swing.JButton();
    jLabelUsername = new javax.swing.JLabel();

    jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
    jLabel3.setText("Schedule Selection");

    jTableCourseListing.setAutoCreateRowSorter(true);
    jTableCourseListing.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
    jTableCourseListing.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {"14/WI - Winter 2014", "No conflicts"},
        {"14/FA - Fall 2014", "No conflicts"},
        {"15/WI - Winter 2015", "Conflicts may exist!"}
      },
      new String [] {
        "Term", "Status"
      }
    ) {
      Class[] types = new Class [] {
        java.lang.String.class, java.lang.String.class
      };

      public Class getColumnClass(int columnIndex) {
        return types [columnIndex];
      }
    });
    jScrollPane1.setViewportView(jTableCourseListing);

    jBtnBackSS.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
    jBtnBackSS.setText("Back");
    jBtnBackSS.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jBtnBackSSActionPerformed(evt);
      }
    });

    jBtnSubmitSS.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
    jBtnSubmitSS.setText("Submit");
    jBtnSubmitSS.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jBtnSubmitSSActionPerformed(evt);
      }
    });

    jLabelUsername.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
    jLabelUsername.setText("3 Schedules Found");

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel3)
          .addComponent(jLabelUsername)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(10, 10, 10)
            .addComponent(jBtnBackSS)
            .addGap(18, 18, 18)
            .addComponent(jBtnSubmitSS))
          .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 711, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel3)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabelUsername)
        .addGap(5, 5, 5)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jBtnSubmitSS)
          .addComponent(jBtnBackSS))
        .addContainerGap(22, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );
  }// </editor-fold>//GEN-END:initComponents

  private void jBtnSubmitSSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSubmitSSActionPerformed
    CSMS.switchTo("CONFLICTS");
  }//GEN-LAST:event_jBtnSubmitSSActionPerformed

  private void jBtnBackSSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBackSSActionPerformed
    CSMS.switchTo("HOME");
  }//GEN-LAST:event_jBtnBackSSActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jBtnBackSS;
  private javax.swing.JButton jBtnSubmitSS;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabelUsername;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTable jTableCourseListing;
  // End of variables declaration//GEN-END:variables
}
