<<<<<<< HEAD
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package CSSCS421;

/**
 *
 * @author steev_000
 */
public class JPanelHome extends javax.swing.JPanel {

  /**
   * Creates new form NewJPanel1
   */
  public JPanelHome() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jLabel3 = new javax.swing.JLabel();
    jBtnSearchSched = new javax.swing.JButton();
    jBtnVerifySched = new javax.swing.JButton();
    jBtnGenerateSched = new javax.swing.JButton();
    jBtnSched = new javax.swing.JButton();

    jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
    jLabel3.setText("Schedule Adjustment");

    jBtnSearchSched.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
    jBtnSearchSched.setText("Search Scehdule");
    jBtnSearchSched.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jBtnSearchSchedActionPerformed(evt);
      }
    });

    jBtnVerifySched.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
    jBtnVerifySched.setText("Verify Schedule");

    jBtnGenerateSched.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
    jBtnGenerateSched.setText("Generate Schedule");

    jBtnSched.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
    jBtnSched.setText("Something Schedule");

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel3)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(jBtnGenerateSched, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(jBtnSearchSched, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGap(18, 18, 18)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(jBtnSched, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(jBtnVerifySched, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel3)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jBtnSearchSched)
          .addComponent(jBtnVerifySched))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jBtnGenerateSched)
          .addComponent(jBtnSched))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );
  }// </editor-fold>//GEN-END:initComponents

  private void jBtnSearchSchedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSearchSchedActionPerformed
    CSMS.switchTo("COURSE SEARCH");
  }//GEN-LAST:event_jBtnSearchSchedActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jBtnGenerateSched;
  private javax.swing.JButton jBtnSched;
  private javax.swing.JButton jBtnSearchSched;
  private javax.swing.JButton jBtnVerifySched;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JPanel jPanel1;
  // End of variables declaration//GEN-END:variables
}
=======
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package CSSCS421;

/**
 *
 * @author steev_000
 */
public class JPanelHome extends javax.swing.JPanel {

  /**
   * Creates new form NewJPanel1
   */
  public JPanelHome() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jLabel3 = new javax.swing.JLabel();
    jBtnSearchSched = new javax.swing.JButton();
    jBtnVerifySched = new javax.swing.JButton();
    jBtnGenerateSched = new javax.swing.JButton();
    jBtnSched = new javax.swing.JButton();

    jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
    jLabel3.setText("Schedule Adjustment");

    jBtnSearchSched.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
    jBtnSearchSched.setText("Search Schedule");
    jBtnSearchSched.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jBtnSearchSchedActionPerformed(evt);
      }
    });

    jBtnVerifySched.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
    jBtnVerifySched.setText("Verify Schedule");

    jBtnGenerateSched.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
    jBtnGenerateSched.setText("Generate Schedule");

    jBtnSched.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
    jBtnSched.setText("Something Schedule");

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel3)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jBtnGenerateSched)
              .addComponent(jBtnSearchSched))
            .addGap(18, 18, 18)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jBtnVerifySched)
              .addComponent(jBtnSched))))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel3)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jBtnSearchSched)
          .addComponent(jBtnVerifySched))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jBtnGenerateSched)
          .addComponent(jBtnSched))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );
  }// </editor-fold>//GEN-END:initComponents

  private void jBtnSearchSchedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSearchSchedActionPerformed
    CSMS.switchTo("COURSE SEARCH");
  }//GEN-LAST:event_jBtnSearchSchedActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jBtnGenerateSched;
  private javax.swing.JButton jBtnSched;
  private javax.swing.JButton jBtnSearchSched;
  private javax.swing.JButton jBtnVerifySched;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JPanel jPanel1;
  // End of variables declaration//GEN-END:variables
}
>>>>>>> origin/master
